routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Seo;


View::composer('*', function ($view) {
    //
    $baseUrl=url('/');
    $currentUrl=url()->current();
    $currentUrl=str_replace($baseUrl,"",$currentUrl); 
    $seo = Seo::where('url', '=', 'https://servicedbyone.com'.$currentUrl)->first();

    $view->with('seo',$seo);

});

Auth::routes(['verify' => true]);
Route::get('/auth/set-password', 'User\PasswordController@get')->name('auth.setPassword.get');
Route::post('/auth/set-password', 'Auth\PasswordController@post')->name('auth.setPassword.post');

Route::get('social/login/{provider}', 'Auth\SocialController@login')->name('social.login');
Route::get('social/callback/{provider}', 'Auth\SocialController@callback')->name('social.callback');

Route::get('/dashboard', 'User\HomeController@dashboard')->name('user.dashboard')->middleware('auth');
Route::get('/settings', 'User\SettingsController@index')->name('user.settings');
Route::post('/settings/updateInfo', 'User\SettingsController@updateInfo')->name('user.settings.updateInfo');
Route::post('/settings/updatePassword', 'User\SettingsController@updatePassword')->name('user.settings.updatePassword');

Route::get('/service-request/{id}', 'User\ServiceRequestController@show')->name('user.service-requests.show');
Route::get('/service-request/{hash}/invoice', 'User\ServiceRequestController@invoice')->name('user.service-requests.invoice');
Route::post('/service-request/{id}/invoice', 'User\ServiceRequestController@charge')->name('user.service-requests.charge');
Route::post('/service-request/{id}/invoice/json', 'User\ServiceRequestController@chargeJson')->name('user.service-requests.chargeJson');


// Admin Home Routes
Route::get('/admin', 'Admin\HomeController@dashboard')->name('admin.dashboard');
Route::resource('/admin/users', 'Admin\UserController');
Route::resource('/admin/seos', 'Admin\SeoController');

// Home Routes
Route::get('/', 'Home\HomeController@index')->name('home');
Route::get('/contact', 'Home\HomeController@contact')->name('contact');
Route::get('/about', 'Home\HomeController@about')->name('about');
Route::get('/careers', 'Home\HomeController@careers')->name('careers');
Route::get('/press', 'Home\HomeController@press')->name('press');

Route::get('/support/guides', 'Home\SupportController@guides')->name('support.guides');
Route::get('/support/how-it-works', 'Home\SupportController@howItWorks')->name('support.howItWorks');
Route::get('/support/safety', 'Home\SupportController@safetyAndInsurance')->name('support.safetyAndInsurance');
Route::get('/support/testimonials', 'Home\SupportController@testimonialsAndReviews')->name('support.testimonialsAndReviews');

Route::get('/customer/how-it-works', 'Home\CustomerController@howItWorks')->name('customer.howItWorks');
Route::get('/customer/safety', 'Home\CustomerController@safety')->name('customer.safety');
Route::get('/customer/near-me', 'Home\CustomerController@nearMe')->name('customer.nearMe');
Route::get('/customer/prices', 'Home\CustomerController@prices')->name('customer.prices');
Route::get('/customer/how-to', 'Home\CustomerController@howTo')->name('customer.howTo');

Route::get('/worker/how-it-works', 'Home\WorkerController@howItWorks')->name('worker.howItWorks');
Route::get('/worker/safety', 'Home\WorkerController@safety')->name('worker.safety');

Route::get("/legal/privacy-policy", "Home\LegalController@privacyPolicy")->name('legal.privacyPolicy');
Route::get("legal/terms-of-use", "Home\LegalController@termsOfUse")->name("legal.termsOfUse");


// Json Service related data routes
Route::get('/admin/services/states', 'Admin\ServiceController@states');
Route::get('/admin/services/cities', 'Admin\ServiceController@cities');
Route::get('/admin/services/areas', 'Admin\ServiceController@areas');
Route::get('/admin/services/categories', 'Admin\ServiceController@categories');
Route::get('/admin/services/questions', 'Admin\ServiceController@questions');

// Admin Service Related Routes
Route::post('/admin/service-requests/{id}/quote', 'Admin\ServiceRequestController@quote')->name('service-requests.quote.update');
Route::delete('/admin/service-questions/{question_id}/choices/{choice_id}', 'Admin\ServiceQuestionController@destroyChoice')->name('service-questions.choices.destroy');
Route::resources([
    '/admin/service-requests' => 'Admin\ServiceRequestController',
    '/admin/service-requests.invoice' => 'Admin\ServiceRequestInvoiceController',
    '/admin/service-questions' => 'Admin\ServiceQuestionController',
    '/admin/service-categories' => 'Admin\ServiceCategoryController',
    '/admin/services' => 'Admin\ServiceController',
]);


// Service Routes
Route::get('/services/{id}', 'ServiceController@show');
Route::post('/services/{id}', 'ServiceController@serviceRequest');
Route::get('/service-categories/{id}', 'ServiceCategoryController@show');
Route::get('/{state_code}', 'LocationController@state');
Route::get('/{state_code}/{city_id}', 'LocationController@city');
Route::get('/{state_code}/{city_slug}/{service_slug}', 'LocationController@service');

app/Models/Seo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Seo extends Model
{
    //
    protected $fillable = [
        'url', 'slug', 'keywords', 'meta_desc',
    ];
}

app/Http/Controllers/Admin/SeoController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\Admin\StoreSeo;
use App\Http\Requests\Admin\UpdateSeo;
use App\Models\User;
use App\Models\Seo;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;

class SeoController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:'.User::ADMIN);
    }

    public function index()
    {
        $seos=Seo::paginate(10);
        return view('admin.seos.index', ['seos' => $seos]);
    }
    //
    public function create()
    { 
        return view( 'admin.seos.create' );
    }


     public function store(StoreSeo $request)
    {
        $validated = $request->validated();
        $seo = Seo::create([
            'url' => $validated['url'],
            'slug' => $validated['slug'],
            'keywords' => $validated['keywords'],
            'meta_desc' => $validated['meta_desc'],
            
        ]);
        return redirect('/admin/seos')->with('status', 'Seo entry successfull!!!');
    }


    public function show(Seo $seo)
    {
        return view('admin.seos.show',['seo1'=>$seo]);
    }

    public function edit(Seo $seo)
    {
        return view('admin.seos.edit',['seo1'=>$seo]);
    }

    public function update(UpdateSeo $request, Seo $seo)
    {
        $validated = $request->validated();
        $seo->slug = $validated['slug'];
        $seo->keywords = $validated['keywords'];
        $seo->meta_desc = $validated['meta_desc'];
        
        $seo->save();
        return redirect('/admin/seos')->with('status', 'Seo entry updated successfull!!!');
    }


    public function destroy(Seo $seo)
    {
        $seo->delete();
        return redirect('/admin/seos')->with('status', 'Seo entry deleted successfull!!!');
    }


}

resources/views/admin/seos/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="">
            <h2 class="">SEO</h2>
        </div>
        @include('errors.list')
        <form action="{{ route('seos.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="slug">URL</label>
                <input name="url" type="text" class="form-control" id="url" placeholder="https://servicedbyone.com/example" value="{{old('url')}}">
            </div>
            <div class="form-group">
                <label for="slug">Title</label>
                <input name="slug" type="text" class="form-control" id="slug" placeholder="" value="{{old('slug')}}">
            </div>
            <div class="form-group">
                <label for="keywords">Key-Words</label>
                <input name="keywords" type="text" class="form-control" id="keywords" placeholder="keyword1,keyword2" value="{{old('keywords')}}">
            </div>
            <div class="form-group">
                <label for="meta_desc">Meta-Description</label>
                <input name="meta_desc" type="text" class="form-control" id="meta_desc" placeholder="Description" value="{{old('meta_desc')}}">
            </div>

            <a class="btn btn-danger" href="{{url()->previous() == url()->current() ? '/admin/seos/' :url()->previous()}}">Cancel</a>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
@endsection

resources/views/admin/seos/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="">
            <h2 class="">Seo#{{$seo1->id}}</h2>
        </div>
        @include('errors.list')
        <form action="{{ route('seos.update', $seo1->id) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="url">URL</label>
                <input name="url" type="text" class="form-control" id="url" placeholder="https://servicedbyone.com/example" value="{{$seo1->url}}" disabled>
            </div>
            <div class="form-group">
                <label for="slug">Title</label>
                <input name="slug" type="text" class="form-control" id="slug" placeholder="" value="{{$seo1->slug}}">
            </div>
            <div class="form-group">
                <label for="keywords">Key-Words</label>
                <input name="keywords" type="text" class="form-control" id="keywords" placeholder="keyword1,keyword2" value="{{$seo1->keywords}}">
            </div>
            <div class="form-group">
                <label for="meta_desc">Meta-Description</label>
                <input name="meta_desc" type="text" class="form-control" id="meta_desc" placeholder="Description" value="{{$seo1->meta_desc}}">
            </div>


            <a class="btn btn-danger" href="{{url()->previous() == url()->current() ? '/admin/seos/'.$seo1->id :url()->previous()}}">Cancel</a>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/admin/seos/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div>
            <h2>SEO</h2>
        </div>

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">URL</th>
                <th scope="col">Title</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($seos as $seo)
            <tr>
                <th scope="row">{{$seo->id}}</th>
                <td>{{$seo->url}}</td>
                <td>{{$seo->slug}}</td>
                <td>
                    <a class="btn btn-primary" href="{{route('seos.show', $seo->id)}}">Show</a>
                    <a class="btn btn-secondary" href="{{route('seos.edit', $seo->id)}}">Edit</a>
                   @include('admin.layouts.deleteform', ['action' => route('seos.destroy', $seo->id), 'id' => $seo->id])
                    
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

        {{ $seos->links() }}
    </div>
@endsection

resources/views/admin/seos/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="">
            <h2 class="">Seo#{{$seo1->id}}</h2>
        </div>
        <table class="table">
            <tbody>
            <tr>
                <th scope="row">#</th>
                <td>{{$seo1->id}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('URL') }}</th>
                <td>{{$seo1->url}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Title') }}</th>
                <td>{{$seo1->slug}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Key-Words') }}</th>
                <td>{{$seo1->keywords}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Meta-Description') }}</th>
                <td>{{$seo1->meta_desc}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Actions') }}</th>
                <td>
                    <a class="btn btn-secondary" href="{{route('seos.edit', $seo1->id)}}">Edit</a>
                    
                    @include('admin.layouts.deleteform', ['action' => route('seos.destroy', $seo1->id), 'id' => $seo1->id])
                   
                </td>
            </tr>
            </tbody>
        </table>
        <div class="clearfix"></div>
        <hr>
        <a class="btn btn-primary" href="{{url()->previous() == url()->current() ? '/admin/seos' :url()->previous()}}">Back</a>
    </div>
@endsection