routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Seo;


View::composer('*', function ($view) {
    //
    $baseUrl=url('/');
    $currentUrl=url()->current();
    $currentUrl=str_replace($baseUrl,"",$currentUrl); 
    $seo = Seo::where('url', '=', 'https://servicedbyone.com'.$currentUrl)->first();

    $view->with('seo',$seo);

});

Auth::routes(['verify' => true]);
Route::get('/auth/set-password', 'User\PasswordController@get')->name('auth.setPassword.get');
Route::post('/auth/set-password', 'Auth\PasswordController@post')->name('auth.setPassword.post');

Route::get('social/login/{provider}', 'Auth\SocialController@login')->name('social.login');
Route::get('social/callback/{provider}', 'Auth\SocialController@callback')->name('social.callback');

Route::get('/dashboard', 'User\HomeController@dashboard')->name('user.dashboard')->middleware('auth');
Route::get('/settings', 'User\SettingsController@index')->name('user.settings');
Route::post('/settings/updateInfo', 'User\SettingsController@updateInfo')->name('user.settings.updateInfo');
Route::post('/settings/updatePassword', 'User\SettingsController@updatePassword')->name('user.settings.updatePassword');

Route::get('/service-request/{id}', 'User\ServiceRequestController@show')->name('user.service-requests.show');
Route::get('/service-request/{hash}/invoice', 'User\ServiceRequestController@invoice')->name('user.service-requests.invoice');
Route::post('/service-request/{id}/invoice', 'User\ServiceRequestController@charge')->name('user.service-requests.charge');
Route::post('/service-request/{id}/invoice/json', 'User\ServiceRequestController@chargeJson')->name('user.service-requests.chargeJson');


// Admin Home Routes
Route::get('/admin', 'Admin\HomeController@dashboard')->name('admin.dashboard');
Route::resource('/admin/users', 'Admin\UserController');
Route::resource('/admin/seos', 'Admin\SeoController');

// Home Routes
Route::get('/', 'Home\HomeController@index')->name('home');
Route::get('/contact', 'Home\HomeController@contact')->name('contact');
Route::get('/about', 'Home\HomeController@about')->name('about');
Route::get('/careers', 'Home\HomeController@careers')->name('careers');
Route::get('/press', 'Home\HomeController@press')->name('press');

Route::get('/support/guides', 'Home\SupportController@guides')->name('support.guides');
Route::get('/support/how-it-works', 'Home\SupportController@howItWorks')->name('support.howItWorks');
Route::get('/support/safety', 'Home\SupportController@safetyAndInsurance')->name('support.safetyAndInsurance');
Route::get('/support/testimonials', 'Home\SupportController@testimonialsAndReviews')->name('support.testimonialsAndReviews');

Route::get('/customer/how-it-works', 'Home\CustomerController@howItWorks')->name('customer.howItWorks');
Route::get('/customer/safety', 'Home\CustomerController@safety')->name('customer.safety');
Route::get('/customer/near-me', 'Home\CustomerController@nearMe')->name('customer.nearMe');
Route::get('/customer/prices', 'Home\CustomerController@prices')->name('customer.prices');
Route::get('/customer/how-to', 'Home\CustomerController@howTo')->name('customer.howTo');

Route::get('/worker/how-it-works', 'Home\WorkerController@howItWorks')->name('worker.howItWorks');
Route::get('/worker/safety', 'Home\WorkerController@safety')->name('worker.safety');

Route::get("/legal/privacy-policy", "Home\LegalController@privacyPolicy")->name('legal.privacyPolicy');
Route::get("legal/terms-of-use", "Home\LegalController@termsOfUse")->name("legal.termsOfUse");


// Json Service related data routes
Route::get('/admin/services/states', 'Admin\ServiceController@states');
Route::get('/admin/services/cities', 'Admin\ServiceController@cities');
Route::get('/admin/services/areas', 'Admin\ServiceController@areas');
Route::get('/admin/services/categories', 'Admin\ServiceController@categories');
Route::get('/admin/services/questions', 'Admin\ServiceController@questions');

// Admin Service Related Routes
Route::post('/admin/service-requests/{id}/quote', 'Admin\ServiceRequestController@quote')->name('service-requests.quote.update');
Route::delete('/admin/service-questions/{question_id}/choices/{choice_id}', 'Admin\ServiceQuestionController@destroyChoice')->name('service-questions.choices.destroy');
Route::resources([
    '/admin/service-requests' => 'Admin\ServiceRequestController',
    '/admin/service-requests.invoice' => 'Admin\ServiceRequestInvoiceController',
    '/admin/service-questions' => 'Admin\ServiceQuestionController',
    '/admin/service-categories' => 'Admin\ServiceCategoryController',
    '/admin/services' => 'Admin\ServiceController',
]);


// Service Routes
Route::get('/services/{id}', 'ServiceController@show');
Route::post('/services/{id}', 'ServiceController@serviceRequest');
Route::get('/service-categories/{id}', 'ServiceCategoryController@show');
Route::get('/{state_code}', 'LocationController@state');
Route::get('/{state_code}/{city_id}', 'LocationController@city');
Route::get('/{state_code}/{city_slug}/{service_slug}', 'LocationController@service');

app/Models/CityArea.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CityArea extends Model
{
    public $timestamps = false;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'city_areas';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'city_id'
    ];

    /**
     * Get the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function getZipAttribute($value)
    {
        return sprintf("%05d", $value);
    }

    /**
     * Get the city that owns the area.
     */
    public function city()
    {
        return $this->belongsTo('App\Models\City', 'city_id', 'id');
    }


    /**
     * Get all of the services for the city area.
     */
    public function services()
    {
        return $this->morphToMany('App\Models\Service', 'location', 'service_location',
            'location_id', 'service_id');
    }
}

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    const LOCATION_TYPE_ALL = 'all';
    const LOCATION_TYPE_IN = 'in';
    const LOCATION_TYPE_EXCEPT = 'except';
    const LOCATION_TYPE_VIRTUAL = 'virtual';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'featured_image', 'slug', 'resized_featured_image',
//        'location_type'
    ];

    /**
     * The services that belong to the service category.
     */
    public function categories()
    {
        return $this->belongsToMany('App\Models\ServiceCategory', 'service_category', 'service_id', 'category_id');
    }

    /**
     * The services that belong to the service category.
     */
    public function questions()
    {
        return $this->belongsToMany('App\Models\ServiceQuestion', 'service_question', 'service_id', 'question_id');
    }

    /**
     * Get all of the states that are assigned this service.
     */
    public function states()
    {
        return $this->morphedByMany('App\Models\State', 'location', 'service_location',
            'service_id', 'location_id');
    }

    /**
     * Get all of the cities that are assigned this service.
     */
    public function cities()
    {
        return $this->morphedByMany('App\Models\City', 'location', 'service_location',
            'service_id', 'location_id');
    }

    /**
     * Get all of the areas that are assigned this service.
     */
    public function areas()
    {
        return $this->morphedByMany('App\Models\CityArea', 'location', 'service_location',
            'service_id', 'location_id');
    }



    /**
     * Get the requests for the service.
     */
    public function requests()
    {
        return $this->hasMany('App\Models\ServiceRequest');
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\StoreServiceRequest;
use App\Http\Requests\Admin\UpdateServiceRequest;
use App\Models\City;
use App\Models\CityArea;
use App\Models\Service;
use App\Models\ServiceCategory;
use App\Models\ServiceQuestion;
use App\Models\State;
use App\Models\User;
use App\Models\Seo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ServiceController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:'.User::ADMIN);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::with('categories')->paginate();


        $baseUrl=url('/');
        $currentUrl=url()->current();
        $currentUrl=str_replace($baseUrl,"",$currentUrl); 
        $seo = Seo::where('url', '=', 'https://servicedbyone.com'.$currentUrl)->first();
        return view('admin.services.index', ['services' => $services,'seo' =>$seo]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.services.create', []);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreServiceRequest $request)
    {
        $validated = $request->validated();
        $service = Service::create([
            'name' => $validated['name'],
            'description' => $validated['description'],
//            'location_type' => $validated['location_type']
        ]);
        $this->handleSlug($service);
        $this->handleLocations($service, $validated['locations']);
        $service->categories()->sync($validated['categories']);
        $service->questions()->sync($validated['questions']);
        $path = isset($validated['featured_image']) ? $validated['featured_image']->store('public/services/'. $service->id) : null;
        $service->update(['featured_image' => $path]);
        $service->update(['resized_featured_image' => $this->resizedImage($path)]);
        return redirect('/admin/services')->with('status', 'Service is created successfully!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {

        $baseUrl=url('/');
        $currentUrl=url()->current();
        $currentUrl=str_replace($baseUrl,"",$currentUrl); 
        $seo = Seo::where('url', '=', 'https://servicedbyone.com'.$currentUrl)->first();
        return view('admin.services.show', ['service' => $service,'seo'=>$seo]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {

        $baseUrl=url('/');
        $currentUrl=url()->current();
        $currentUrl=str_replace($baseUrl,"",$currentUrl); 
        $seo = Seo::where('url', '=', 'https://servicedbyone.com'.$currentUrl)->first();
        return view('admin.services.edit', ['service' => $service,'seo'=>$seo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateServiceRequest $request, Service $service)
    {
        $validated = $request->validated();
        $service->update([
            'name' => $validated['name'],
            'description' => $validated['description'],
//            'location_type' => $validated['location_type']
        ]);
        $this->handleSlug($service);
        $this->handleLocations($service, $validated['locations']);
        $service->categories()->sync($validated['categories']);
        $service->questions()->sync($validated['questions']);
        if(isset($validated['featured_image']))
        {
            if(!is_null($service->featured_image))
                Storage::delete($service->featured_image);
            $path = $validated['featured_image']->store('public/services/' . $service->id);
            $service->update(['featured_image' => $path]);
        }
        return redirect('/admin/services')->with('status', 'Service is updated successfully!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        $service->delete();
        return redirect('/admin/services')->with('status', 'Service is deleted successfully!!!');
    }

    public function categories(Request $request)
    {
        if($request->input('q', false))
        {
            $q = explode('|', $request->input('q'));
            $categories = ServiceCategory::where('name', 'like', '%'.$request->input('q').'%')->paginate();
        }
        else
            $categories = ServiceCategory::paginate();

        return $categories;
    }

    public function states(Request $request)
    {
        if($request->input('q', false))
        {
            $q = explode('|', $request->input('q'));
            if(empty($q[1]))
                $locations = State::where('state', 'like', '%' . $q[0] . '%')->paginate();
            else
                $locations = State::where('state', 'like', '%' . $q[0] . '%')->where('state_code', strtoupper($q[1]))->paginate();
        }
        else
            $locations = State::paginate();

        return $locations;
    }

    public function cities(Request $request)
    {
        if($request->input('q', false))
        {
            $q = explode('|', $request->input('q'));
            if(empty($q[1]))
                $locations = City::where('city', 'like', '%' . $q[0] . '%')->paginate();
            else
                $locations = City::where('city', 'like', '%' . $q[0] . '%')->where('state_code', strtoupper($q[1]))->paginate();
        }
        else
            $locations = City::paginate();

        return $locations;
    }

    public function areas(Request $request)
    {
        if($request->input('q', false))
        {
            $q = $request->input('q');
            $locations = CityArea::where('city', 'like', '%' . $q . '%')
                ->orWhere('zip', 'like', '%' . $q . '%')->paginate();
        }
        else
            $locations = CityArea::paginate();

        return $locations;
    }


    public function questions(Request $request)
    {
        if($request->input('q', false))
            $questions = ServiceQuestion::where('name', 'like', '%'.$request->input('q').'%')->paginate();
        else
            $questions = ServiceQuestion::paginate();

        return $questions;
    }


    private function handleSlug(Service $service)
    {
        $slug = str_slug($service->name);
        $s = Service::where('slug', $slug)
            ->where('id', '!=', $service->id)
            ->first();
        if(!is_null($s))
            $service->update(['slug' => $slug.'-'.$service->id]);
        else
            $service->update(['slug' => $slug]);
    }

    private function handleLocations(Service $service, $selectedLocations)
    {
        $service->states()->sync($selectedLocations);
    }

    private function resizedImage($path)
    {
        $img = \Image::make(storage_path('app/' . $path));
        $img->fit(600, 300);
        $filepath = str_replace('.', '-600x300.', $path);
        $img->save(storage_path('app/' . $filepath));

        return $filepath;

    }
}

resources/views/admin/services/requests/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div>
            <h2>Service Requests</h2>
        </div>

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">User</th>
                <th scope="col">Invoice</th>
                <th scope="col">Created At</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($requests as $request)
            <tr>
                <th scope="row">{{$request->id}}</th>
                <td>
                    @if($request->user)
                        <a href="{{route('users.show', $request->user->id)}}">{{ $request->user->id . ' | ' . $request->user->email }}</a>
                    @endif
                </td>
                <td>
                    @if($request->invoice)
                        @if(is_null($request->invoice->charge_id))
                            <p class="text-danger">Not Paid</p>
                        @else
                            Charge ID: {{$request->invoice->charge_id}}
                        @endif
                    @else
                        <p class="text-danger">No Invoice Found</p>
                    @endif
                </td>
                <td>{{$request->created_at->toRfc850String()}}</td>
                <td>
                    <a class="btn btn-primary" href="{{route('service-requests.show', $request->id)}}">Show</a>
                    {{--<a class="btn btn-secondary" href="{{route('service-requests.edit', $request->id)}}">Edit</a>--}}
                    @include('admin.layouts.deleteform', ['action' => route('service-requests.destroy', $request->id), 'id' => $request->id])
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

        {{ $requests->links() }}
    </div>
@endsection

resources/views/admin/services/requests/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="">
            <h2 class="">Service Request#{{$request->id}}</h2>
        </div>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <table class="table">
            <tbody>
            <tr>
                <th scope="row">#</th>
                <td>{{$request->id}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Service ID') }}</th>
                <td>{{$request->service_id}} | {{$request->service->name}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Location') }}</th>
                <td>{{$request->location->zip}} | {{$request->location->city->city}} | {{$request->location->city->state_code}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Created At') }}</th>
                <td>{{$request->created_at->toRfc850String()}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Updated At') }}</th>
                <td>{{$request->updated_at->toRfc850String()}}</td>
            </tr>
            <tr>
                <th scope="row">{{ __('Actions') }}</th>
                <td>
                    @include('admin.layouts.deleteform', ['action' => route('service-requests.destroy', $request->id), 'id' => $request->id])
                </td>
            </tr>
            </tbody>
        </table>
        <div class="clearfix"></div>
        <hr>

        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Question</th>
                    <th scope="col">Answer</th>
                </tr>
                </thead>
                <tbody>
                @foreach($request->service->questions as $question)
                    <tr>
                        <td>{{$question->id}} | {{$question->name}} | {{$question->question}}</td>
                        <td>
                            @php($a = $request->answers->where('question_id', $question->id)->first())
                            @if(is_null($a))
                                <p class="text-danger">No Answer</p>
                            @else
                                @if($question->type == \App\Models\ServiceQuestion::TYPE_BOOLEAN)
                                    {{ $a->answer->answer ? 'Yes' : 'No' }}
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_TEXT)
                                    {{ $a->answer->answer }}
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_TEXT_MULTILINE)
                                    {{ $a->answer->answer }}
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_TIME)
                                    {{ $a->answer->answer }}
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_DATE)
                                    {{ $a->answer->answer }}
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_DATE_TIME)
                                    {{ $a->answer->answer }}
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_FILE)
                                    <img src="{{ asset(str_replace("public","storage", $a->answer->file_path)) }}" alt="" style="width: 100%">
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_FILE_MULTIPLE)
                                    @foreach($request->answers->where('question_id', $question->id) as $c)
                                        <img src="{{ asset(str_replace("public","storage", $c->answer->file_path)) }}" alt="" style="width: 100%"><br />
                                    @endforeach
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_SELECT)
                                    @foreach($request->answers->where('question_id', $question->id) as $c)
                                        {{ $c->answer->choice->id }} | {{ $c->answer->choice->choice }}<br />
                                    @endforeach
                                @elseif($question->type == \App\Models\ServiceQuestion::TYPE_SELECT_MULTIPLE)
                                    @foreach($request->answers->where('question_id', $question->id) as $c)
                                        {{ $c->answer->choice->id }} | {{ $c->answer->choice->choice }}<br />
                                    @endforeach
                                @endif
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="clearfix"></div>
        <hr>

        <div class="">
            <h2 class="">Invoice</h2>
        </div>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        @include('errors.list')

        @if($request->invoice)
            @if(is_null($request->invoice->charge_id))
                <form action="{{ route('service-requests.invoice.update', [$request->id, $request->invoice->id]) }}" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="sort-container">
                        @foreach($request->invoice->details as $row)
                            <div class="sort-item" id="row-{{$loop->iteration}}">
                                <input type="hidden" class="sort-order-value" name="sort-order[{{$loop->index}}]" value="{{$loop->iteration}}">
                                <label class="sr-only" for="inlineFormInputGroup">Detail</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text dragdrop-handle"><i class="fa fa-arrows"></i></div>
                                    </div>
                                    <input name="detail[{{$loop->index}}]" type="text" class="form-control" placeholder="Detail" required min='0' value="{{$row->detail}}">
                                    <input name="cost[{{$loop->index}}]" type="number" step="0.01" class="form-control" placeholder="$0.0" required min='0' value="{{$row->cost}}">
                                    <input name="quantity[{{$loop->index}}]" type="number" step="1" class="form-control" placeholder="Quantity" min='0' required value="{{$row->quantity}}">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-danger delete-handle" type="button" data-row="1">Delete</button>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div><!-- /.sort-container -->

                    <div class="form-group form-check">
                        <input name="mail" type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Send Email to User?</label>
                    </div>

                    <button id="addRow" class="btn btn-outline-primary" type="button">Add Row</button>
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            @else
                <div class="alert alert-info">Invoice for this request is already paid. And charge id is: {{$request->invoice->charge_id}}</div>
            @endif
        @else
            <form action="{{ route('service-requests.invoice.store', $request->id) }}" method="POST">
                @csrf

                <div class="sort-container">
                    <div class="sort-item" id="row-1">
                        <input type="hidden" class="sort-order-value" name="sort-order[]" value="1">
                        <label class="sr-only" for="inlineFormInputGroup">Detail</label>
                        <div class="input-group mb-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text dragdrop-handle"><i class="fa fa-arrows"></i></div>
                            </div>
                            <input name="detail[]" type="text" class="form-control" placeholder="Detail" required min='0'>
                            <input name="cost[]" type="number" step="0.01" class="form-control" placeholder="$0.0" required min='0'>
                            <input name="quantity[]" type="number" step="1" class="form-control" placeholder="Quantity" min='0' required>
                            <div class="input-group-append">
                                <button class="btn btn-outline-danger delete-handle" type="button" data-row="1">Delete</button>
                            </div>
                        </div>
                    </div>
                </div><!-- /.sort-container -->

                <div class="form-group form-check">
                    <input name="mail" type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Send Email to User?</label>
                </div>

                <button id="addRow" class="btn btn-outline-primary" type="button">Add Row</button>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        @endif
        <div class="clearfix"></div>
        <hr>
        <a class="btn btn-primary" href="{{url()->previous() == url()->current() ? '/admin/service-requests' :url()->previous()}}">Back</a>
    </div>
@endsection


@section('scripts')
    <script type="text/javascript">
        $(document).ready(function(){
            var count = 1;
            $('#addRow').click(function(){
                count++;
                $('.sort-container').append("<div class=\"sort-item\" id=\"row-"+count+"\">\n" +
                    "                    <input type=\"hidden\" class=\"sort-order-value\" name=\"sort-order[]\" value=\""+count+"\">\n" +
                    "                    <label class=\"sr-only\" for=\"inlineFormInputGroup\">Detail</label>\n" +
                    "                    <div class=\"input-group mb-2\">\n" +
                    "                        <div class=\"input-group-prepend\">\n" +
                    "                            <div class=\"input-group-text dragdrop-handle\"><i class=\"fa fa-arrows\"></i></div>\n" +
                    "                        </div>\n" +
                    "                        <input name=\"detail[]\" type=\"text\" class=\"form-control\" placeholder=\"Detail\" required min='0'>\n" +
                    "                        <input name=\"cost[]\" type=\"number\" step=\"0.01\" class=\"form-control\" placeholder=\"$0.0\" required min='0'>\n" +
                    "                        <input name=\"quantity[]\" type=\"number\" step=\"1\" class=\"form-control\" placeholder=\"Quantity\" min='0' required>\n" +
                    "                        <div class=\"input-group-append\">\n" +
                    "                            <button class=\"btn btn-outline-danger delete-handle\" type=\"button\" data-row=\""+count+"\">Delete</button>" +
                    "                        </div>\n" +
                    "                    </div>\n" +
                    "                </div>");
            });

            $( '.sort-container' ).on( 'click', '.delete-handle', function () {
                console.log('check');
                var row = $(this).data('row');
                $('#row-'+row).remove();
            });
        });
    </script>
@endsection